create table if not exists person(
    person_id     integer generated by default as identity primary key,
    full_name     varchar(100) not null unique,
    year_of_birth integer      not null check (year_of_birth > 1900)
);
create table if not exists book(
    book_id        integer generated by default as identity primary key,
    person_id      integer references person on update set null on delete set null,
    name           varchar(100) not null unique,
    auther         varchar(100) not null,
    year           integer      not null check (year > 1500),
    date_of_taking timestamp
);